version: '3'

services:
  spark:
    image: docker.io/bitnami/spark
    user: root
    networks:
      dae:
        ipv4_address: 172.1.0.2
    environment:
      - PYTHONIOENCODING=utf8
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./spark/src:/opt/bitnami/spark/src
  spark-worker-1:
    image: docker.io/bitnami/spark
    user: root
    networks:
      dae:
        ipv4_address: 172.1.0.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark/src:/opt/bitnami/spark/src
  spark-worker-2:
    image: docker.io/bitnami/spark
    user: root
    networks:
      dae:
        ipv4_address: 172.1.0.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark/src:/opt/bitnami/spark/src
  mongodb:
    image: mongo
    restart: always
    networks:
      dae:
        ipv4_address: 172.1.0.10
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/db:/data/db
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      dae:
        ipv4_address: 172.1.0.30
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes  
  postgres:
    image: "postgres:13"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: recentchange
    restart: always
    networks:
      dae:
        ipv4_address: 172.1.0.20
    ports:
        - "6432:5432"
    volumes:
        - ./pgdata:/var/lib/postgresql/data  
networks:
  dae:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24